### ISSUE TITLE
Add overlay_opacity option

### ISSUE THREAD

**Issue by ghost** [jackwanders/GalleryView#47]

**Comment by S-ed** [comment]
There is no need in that.
You can customize it through CSS.
Just edit `jquery.galleryview-3.0-dev.css` (by default).

``` css
.gv_overlay {
    ...
    background: rgba(128, 128, 128, 0.5); /*or background-color:*/
    ...
}
```

or

``` css
.gv_overlay {
    ...
    opacity: 0.5; /*that makes content also transparent*/
    ...
}
```

**Comment by S-ed** [comment]
Or. You can even make it so:

``` css
.gv_overlay {
    ...
    background: #222;
    ...
    opacity: 0.3; /*opacity of transition when mouse outside of overlay*/
    transition: opacity 1s; /*speed of transition when mouse leaves*/
    -moz-transition: opacity 1s; /*fix for Firefox 4 */
    -webkit-transition: opacity 1s; /*fix for Safari and Chrome */
    -o-transition: opacity 1s; /*fix for Opera */
    ...
}

.gv_overlay:hover {
    ...
    opacity: 1; /*opacity of transition when mouse intside overlay*/
    transition: opacity 1s; /*speed of transition when mouse hover*/
    -moz-transition: opacity 1s; /*fix for Firefox 4 */
    -webkit-transition: opacity 1s; /*fix for Safari and Chrome */
    -o-transition: opacity 1s; /*fix for Opera */
    ...
}
```

Well, `transition` is a complex feature, so Google for it if interested.
